---

- include_role:
    name: plumelo.mysql
    private: true
  vars:
    mysql_databases:
      - name: "{{ packagist_database_name }}"
    mysql_users:
      - name: "{{packagist_database_user}}"
        pass: "{{packagist_database_pass}}"
        privs:
          - "{{ packagist_database_name }}.*:ALL"
        hosts:
          - "{{packagist_database_host}}"
    when: packagist_database == 'mysql'
