---

- name: Ensure packagist user exist
  user: name='{{ packagist_user }}' state=present

- name: Ensure packagist directory exist | /srv/packagist
  file: path='{{ packagist_path }}' state=directory owner='{{ packagist_user }}' group='{{ packagist_user }}' mode='0755'
  with_items:
    - '{{ packagist_path }}'
    - '{{ packagist_path }}/vendor/.cache'

- name: Install composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=a+x

- name: Download packagist
  unarchive:
    src: '{{ packagist_download_url }}'
    dest: '{{ packagist_path }}'
    remote_src: yes
    extra_opts: '--strip-components=1'
    owner: '{{ packagist_user }}'
    group: '{{ packagist_user }}'
    creates: '{{ packagist_path }}/composer.json'
  register: packagist_download_status
