---

# tasks file for composer-role
- name: Install prerequsites
  apt:
    update_cache: true
    pkg: "{{ item }}"
    state: present
  with_items:
    - zip
    - unzip
    - acl
    - git

- import_tasks: download.yml
- import_tasks: php.yml
- import_tasks: nginx.yml
- import_tasks: database.yml
- import_tasks: redis.yml
- import_tasks: install.yml
