---

- include_role: name=nbz4live.php-fpm private=true
  vars:
    php_fpm_version: 7.1
    php_fpm_apt_packages:
      - php7.1-fpm
      - php-curl
      - php-xml
      - php-mysql
    php_fpm_pools:
      - name: packagist
        user: "{{ packagist_websrv_user }}"
        group: "{{ packagist_websrv_user }}"
        listen: 9001
        chdir: /
